### PR TITLE
Updated README with dependency and note about double opt-in

### PR DESCRIPTION
**Pull request by DanBlakeman**
Hi, thanks for the gem, works a treat, just what we we're after! :+1: 

I was getting an 'Unitialized Constant' from 'lib/devise_campaignable/adapters/mailchimp.rb:78'
until i added Gibbon to my gemfile. So just updated the readme with a note to install this too! :) 

Also added a note to say that by default 'double opt-in' for subscribers is set to false (as this was a plus point worth mentioning for me!)

Thanks for sharing! 

Dan

### CODE REVIEW

**Comment by SirRawlins** [comment]
Fantastic, thanks Dan,

I'll get these changes merged in next week.

Shall keep you posted.

Rob

Hi, thanks for the gem, works a treat, just what we we're after! [image:
:+1:]

I was getting an 'Unitialized Constant' from
'lib/devise_campaignable/adapters/mailchimp.rb:78'
until i added Gibbon to my gemfile. So just updated the readme with a note
to install this too! :)

Also added a note to say that by default 'double opt-in' for subscribers is
set to false (as this was a plus point worth mentioning for me!)

Thanks for sharing!

## Dan

You can view, comment on, or merge this pull request online at:

  https://github.com/sorry-app/devise_campaignable/pull/1
Commit Summary
- Updated README with dependency and note about double opt in

File Changes
- _M_ README.md
  https://github.com/sorry-app/devise_campaignable/pull/1/files#diff-0
  (7)

Patch Links:
- https://github.com/sorry-app/devise_campaignable/pull/1.patch
- https://github.com/sorry-app/devise_campaignable/pull/1.diff

—
Reply to this email directly or view it on GitHub
https://github.com/sorry-app/devise_campaignable/pull/1.

**Comment by SirRawlins** [comment]
Morning Dan,

I'm just taking another look at this, and I note that Gibbon is listed in the gemspec as a runtime dependancy so should be installed along with the devise_campaignable gem, you shouldn't have to install it by yourself.

How did you install devise_campaignable? Did you use bundler? Or install in manutally using 'gem install...'?

Thanks,

Rob

**Comment by jaimeiniesta** [comment]
I saw this same 'Uninitialized Constant' referring to Gibbon on a friend's project. It was fixed by explicitly including the Gibbon dependency on the Gemfile, but unfortunately I couldn't investigate more to find the cause of this.

**Comment by SirRawlins** [comment]
@jaimeiniesta thanks for letting me know. This quite odd, perhaps it's a versioning issue whereby it can't find the right version of gibbon.

Clearly an issue so I'll merge in this PR and tackle the core issue later.

**Comment by DanBlakeman** [comment]
Apologies, hadn't seen your reply until now!

I installed via bundler! :)

**Comment by jaimeiniesta** [comment]
BTW, I could reproduce this bug as well, I had to explicitly include `gibbon` on the Gemfile.

**Comment by SirRawlins** [comment]
Thanks for the heads up on this. Still confused as Gibbon is listed in the Gemspec as a runtime dependancy. I have created issue #4 to track progress. If you have any ideas or comments drop them under the new issue.

**Pull request merged**
